### ISSUE TITLE
"Open auth page in the default browser" fails

### ISSUE THREAD

**Issue by avi12** [fregante/chrome-webstore-upload-keys#2]
https://github.com/fregante/chrome-webstore-upload-keys/blob/049b6992e3c1fe673719067987d135d48ff015cb/cli.js#L109-L111
I'm on Windows 10. Instead of opening in the default browser, it simply opened up File Explorer

**Comment by fregante** [comment]
Thank you for reporting it. I'll look into it

**Comment by fregante** [comment]
The new version should work. If you have any issues let me know


```
npx chrome-webstore-upload-keys@1.1.5
```
