### ISSUE TITLE
TTY Initialization Failed When Running npx chrome-webstore-upload-keys

### ISSUE THREAD

**Issue by kalilinux-png** [fregante/chrome-webstore-upload-keys#4]
When attempting to run the command `npx chrome-webstore-upload-keys`, I encountered a TTY initialization error. The error message indicates a bad file descriptor. Below are the details of the error for reference.

**Command**:  
```bash
npx chrome-webstore-upload-keys
```

**Error Message**:  
```
T  Follow the steps at this URL to generate the API keys, then enter them below to generate the refresh token.
   https://github.com/fregante/chrome-webstore-upload-keys
node:tty:93
    throw new ERR_TTY_INIT_FAILED(ctx);
          ^

SystemError [ERR_TTY_INIT_FAILED]: TTY initialization failed: uv_tty_init returned EBADF (bad file descriptor)
    at new WriteStream (node:tty:93:11)
    at oD.prompt (file:///C:/Users/Sachin%20Ughade/node_modules/chrome-webstore-upload-keys/dist/index.js:368:748)
    at Object.te (file:///C:/Users/Sachin%20Ughade/node_modules/chrome-webstore-upload-keys/dist/index.js:384:7)
    at clientId (file:///C:/Users/Sachin%20Ughade/node_modules/chrome-webstore-upload-keys/dist/index.js:270:75)
    at Object.he (file:///C:/Users/Sachin%20Ughade/node_modules/chrome-webstore-upload-keys/dist/index.js:452:632)
    at file:///C:/Users/Sachin%20Ughade/node_modules/chrome-webstore-upload-keys/dist/index.js:268:78
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_TTY_INIT_FAILED',
  info: {
    errno: -4083,
    code: 'EBADF',
    message: 'bad file descriptor',
    syscall: 'uv_tty_init'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}

Node.js v20.16.0
```

**Environment**:  
- **Node.js Version**: v20.16.0  
- **Operating System**: Windows 11 
- **Terminal/CLI**:Bash

**Steps to Reproduce**:  
1. Open the terminal/command prompt.
2. Run the command `npx chrome-webstore-upload-keys`.
3. Observe the error output.

**Expected Behavior**:  
The command should prompt for Refresh Token without any TTY initialization errors.

**Additional Information**:  
- I followed the instructions provided at the [GitHub URL](https://github.com/fregante/chrome-webstore-upload-keys) to generate the API keys before running the command.
- This issue seems related to the terminal environment not supporting TTY operations.

**Potential Solutions**:  
- Please advise on any possible workarounds or fixes for this issue.  
- Is there a way to run this command in a non-TTY mode?

Thank you for your assistance!

**Comment by fregante** [comment]
It looks like this issue is related to git bash and all the fixes online mention "don't use git bash", so that's going to be my advice too. 

Windows now comes with a nice terminal and I think it's best to not use obsolete products: 

https://learn.microsoft.com/en-us/windows/terminal/
